version: '3'

tasks:
  proto:
    cmds:
      - |
        protoc --proto_path=./proto \
          --go_opt=paths=source_relative --go_out=./api \
          --go-grpc_opt=paths=source_relative --go-grpc_out=./api \
          ./proto/*.proto