version: '3'

tasks:
  proto:
    cmds:
      - |
        protoc --proto_path=./proto \
          --go_opt=paths=source_relative --go_out=./api \
          --go-grpc_opt=paths=source_relative --go-grpc_out=./api \
          ./proto/*.proto

  build:server:
    cmds:
      - go build -o vehicles_system_server ./cmd/server

  build:client:
    cmds:
      - go build -o vehicles_system_client ./cmd/client

  build:all:
    cmds:
      - task build:server
      - task build:client

  docker:build:
    cmds:
      - docker build -t vehicles_system_server .